name: Build Unity Self-Auth
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image Tag'
        required: true
        default: 'latest'

jobs:
  build-unity-self-auth:
    runs-on: self-hosted
    steps:
      - name: clear cache
        run: |
          docker system prune -a --force
        shell: bash

      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1     
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            deserializeme/unity-self-auth
          
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ./docker/Dockerfile
          build-args: |
          context: ./docker/
          push: ${{ github.event_name != 'pull_request' }}
          tags: deserializeme/unity-self-auth:${{github.event.inputs.tag}}
          labels: ${{ steps.meta.outputs.labels }}
